/** קטגוריות ספק — תואם wedding-web / DB */
export const VENDOR_CATEGORY_OPTIONS: { id: string; label: string }[] = [
  { id: 'dj', label: 'די ג׳יי / DJ' },
  { id: 'band', label: 'להקה חיה' },
  { id: 'singer', label: 'זמר/ת סולו' },
  { id: 'photography', label: 'צילום' },
  { id: 'videography', label: 'וידאו / צילום סרטון' },
  { id: 'drone', label: 'צילום רחפן' },
  { id: 'venue', label: 'גן אירועים / אולם' },
  { id: 'catering', label: 'קייטרינג' },
  { id: 'bar', label: 'בר אלכוהול / ברמנים' },
  { id: 'cakes', label: 'עוגות וקינוחים' },
  { id: 'flowers', label: 'עיצוב פרחים' },
  { id: 'design', label: 'עיצוב אירוע / הפקה' },
  { id: 'lighting', label: 'תאורה והגברה' },
  { id: 'rentals', label: 'השכרת ציוד (שולחנות, כיסאות…)' },
  { id: 'bridal', label: 'שמלות כלה / חליפות' },
  { id: 'beauty', label: 'איפור ושיער' },
  { id: 'jewelry', label: 'תכשיטים' },
  { id: 'officiant', label: 'רב / עורך טקס' },
  { id: 'mc', label: 'מנחה / קריינות' },
  { id: 'kids', label: 'פעילות ילדים / מנפחים' },
  { id: 'security', label: 'אבטחה' },
  { id: 'valet', label: 'חניה / ולט' },
  { id: 'transport', label: 'הסעות' },
  { id: 'stationery', label: 'הזמנות נייר / מיתוג' },
  { id: 'gifts', label: 'מתנות לאורחים' },
  { id: 'fireworks', label: 'זיקוקין / אפקטים' },
  { id: 'chuppah', label: 'חופה / טקס' },
  { id: 'planner', label: 'מתכנן/ת אירועים' },
  { id: 'honeymoon', label: 'חופשה / יעד דביל' },
  { id: 'other', label: 'אחר (פרט בהערות)' },
]
